### ISSUE TITLE
Make easy update : Separate gen file et hand written file

### ISSUE THREAD

**Issue by nicolasboulay** [kujtimiihoxha/kit#2]
The need to modify generated .go file, looks like the need to modify the .asm file generated by a c compiler.

It's complex to update the generated part, when the generator need to be re-run and the file are modified by hand.

It will be great if kit could be used with "go generate", and if there inputs are considered as source code.

**Comment by kujtimiihoxha** [comment]
Hey @nicolasboulay, By modifying the generated files do you mean the `*_gen.go` files ? 

If yes than those are not meant to be modified, they just put things together e.x `Get all endpoints inside the Endpoints interface and so on.`

While using `kit` for some of my projects I created I also saw that it has some issues with needing to modify generated files, that's why I needed to modify it to better generate files for that project see `sh_gen` branch, the good thing is that it is quite easy to modify.

If you have any idea or example of how we could use `go generate` please outline them here.

I would also appreciate any PR improving how `kit` works.

Thanks for your feedback.

**Comment by nicolasboulay** [comment]
I mean all the file produce by kit. I maid a mistake following https://medium.com/@kujtimii.h/creating-a-todo-app-using-gokit-cli-20f066a58e1 (wrong import into service.go), so i must delete almost all files to run kit and make it compile.
Maybe you could separate file generated as example (service.go) and generated file using them (with command options ?) that will need to be updated. It will be great if those generated file are temporary files and not really like normal .go source code.

I will look at sh_gen branches. Have you a documentation on how to handle update of the source code ? (expanding service interface to change the generated files, how to avoid to destroy hand code,...)

**Comment by kujtimiihoxha** [comment]
Actually every file that does not end with `*_gen.go` can be edited and the generator should not override any change you made in them. 

The only issue is that the generator does not have any kind of `Update` function e.x if you first except an `int` as a parameter than remember that it is a `string` you would need to manually update endpoints/http/middlewares. 

To be able to update those things it would make the generator far more complex.

**Comment by nicolasboulay** [comment]
Nobody want such complexity. java enable it, and it's a huge mess.

That's why i suggest to split "kit" files and the hand written one. It's so easy to delete and regenerate everything and use the generated main.go or another one, for example. The complexity is on choosing an architecture that make this possible.

I'm a gokit beginner that struggle to understand all the architecture. So i don't see all problems.

From my point of view, the service.go file is the center of everything. So the "//go:generate kit g s todo -w --gorilla -type=todoService" could be in it, and you could generate all the repositories beside the file.

If you need more informations like path naming, HTTP verb, kit could use "tag" inside the service structure for such data (as json does).

You could add also an "example" generation for the first template of a middleware according to the current service.go. This helps too, even without update functionality.

**Comment by kujtimiihoxha** [comment]
Yep I like this idea, the only issue I see is that most of the times you would like to be able to update the decoder/encoder for HTTP and autogenerating them will limit you to use one standard (e.x How the response/request should look like) also what if you are not using JSON but XML these sort of things need to be manually edited.

I can imagine generating the endpoints automatically, I found that most of the times I do not edit the endpoints files at all, but the HTTP handler yes.

I could create a standard that will use Gokit as the backend which would make it more like a framework, but Gokit does not seem to want to limit the users on how they use the library.

If you are up to we could start a new branch and test stuff out, I would be more than happy to test out how we could make using Gokit easier for beginners 😉

**Comment by nicolasboulay** [comment]
Beginners have always too much to learn. If kit makes sensible default options, this is nice. When the code and experience get bigger, it shall offer more choices and controls. There is already a lot of good practice available for micro-service that could be followed.

Kit needs to have clear inputs and outputs. If output could be considered as asm file for c compiler, you win (note that you could still add asm file beside the C source code). Inputs shall be saved in version control, but it's not an obligation for generated outputs. To ease test, the generated code should stay in it's own repository and could be deleted and recreated without worry for the business code.

For JSON, it looks easy because you have the tag to control a little how the field are serialised. I don't know for XML or grpc. 

I see kit as a way to add strong and real server stuff around business code (in real world server, middleware are needed).

For code that need to be modified by hand, it should be written in a well identified way : specific package or specific function naming. This function will be identified and will be called by the generated code. This avoid complex "injection" at the top level. With this kind of behaviour, modifying generated code means adding the right function in the right package.

Does it sound good to you ? If i can trust kit, that will save me lot of time !

**Comment by kujtimiihoxha** [comment]
Yep I get what you are saying. Just to get a feel for what you would need to implement let's consider this simple service.

`MyService`
```
type MyService interface {
   Get(ctx context.Context)(list []string , err error)
   GetById(ctx context.Context, id int)(s string , err error)
   AddOne(ctx context.Context, s string)(err error)
}
```

To make this work you need:
 - Endpoints
 - Handler

Let's say we want an HTTP endpoint and we want these URLs
- `GET /string`
- `GET /string/{id}`
- `POST /string   body {'my_string':"hello"}`

How would you propose to separate files and tell the generator how to create the HTTP handler for those endpoints.

Try running `kit` as it is right now for the above service and see what files are generated all of them need to be generated by the `new version` of `kit` because the way the gokit library is create it is quite verbose and I 100% agree that the way to go with this would be to abstract all that complexity away from the developer.

**Comment by nicolasboulay** [comment]
For me service.go should be in a "user controlled" repository, and pkg/ should a pkg_gen/ and cmd_gen/. a pkg/ could be created to have an example to start.

I see that only POST are currently generated.

I suggest to use tags, this looks like :

```
type MyService interface {
   Get(ctx context.Context)(list []string , err error)             `kit:"GET","/string"`
   GetById(ctx context.Context, id int)(s string , err error) `kit:"GET","/string/{id}"`
   AddOne(ctx context.Context, s string)(err error)            `kit:"POST","/string"`
}
```

**Comment by kujtimiihoxha** [comment]
Actually, you can not use tags on an `interface` like that. But maybe we could find another way to get that information to the generator.

I'll be thinking of something.

**Comment by nicolasboulay** [comment]
I hope you find  a way to link the path, the http verb, and the service interface with an easy way.

I try to understand the generated code, but it's more complex and different than the gokit example.

**Comment by kujtimiihoxha** [comment]
I think that gokit has created some official generator that maybe will better suit you I have not personally tried it though.

https://github.com/go-kit/kit/tree/master/cmd/kitgen

**Comment by nicolasboulay** [comment]
https://github.com/go-kit/kit/tree/master/cmd/kitgen is very simple.

https://github.com/Ayiga/go-kit-middlewarer add more stuff (middleware), use generate, but don't generate main file.

Your generator is one of the more advanced.

**Comment by kujtimiihoxha** [comment]
Hey there @nicolasboulay just wanted to let you know that I am working on something to make it easier to update the service it will use `annotations` and will look something like : 

```go
type MyService interface{
	// @Http(method='Get',url='/test/{id}')
	// @Middleware("Auth","Test")
	// @EpMiddleware("Instrumenting")
	Get(ctx context.Context, in io.GetRequest)(out io.GetResponse, err error)
}
```

Then I am thinking of using tags for defining which part of the request is mapped where in the `GetRequest` structure like:

```go
type GetRequest struct {
	Id uint `in:"url" name:"my_id"`
	SomeQueryParam string `in:"query" name:"my_name"`
	Body GetRequestBody `in:"body"` // if for e.x you have extra load in body
}
type GetRequestBody struct {
	Some string `json:"some"`
	Value string `json:"value"`
}
```
Alternatively if the complete request is in `body` I am thinking of using annotations here as well.
```go
// @Body(type='json')
type GetRequest struct {
	Some string `json:"some"`
	Value string `json:"value"`
}
```
And finally, if a user would like to have full control of the decoding the struct could implement:
```go
type WithDecoder interface {
    Decode(ctx context.Context, r *http1.Request) (interface{}, error)
}
```
This would be then used instead of the `default` gokit implementation.

The same as above goes for the response struct.

These are still only ideas (with some small test implementations I have done).
There is no branch that has these implementations yet, but I will try to have something by the end of the week.
One bad thing is that this would break complete backward compatibility but I think its a good step forward.

Let me know your thoughts on this.

**Comment by nicolasboulay** [comment]
It looks nice, to map service and URL. But keep a way to generate xml and protof in the same time. If your generator work well, it will be asked to managed more protocol at the same time.

It will be great to manage many services in the same time, each with it's own code generation. Ayiga/go-kit-middlewarer uses normal http so service are only added to it, so we could add as many service we want.

If you could add a generator-like call to your generator, it will be great :
//go:generate kit-gen --type=MyService

It could be great also to generate client for an already existing service. Usually, client are generated to access to the microservice, but not to access an external microservice . I imagine you can trick the generator to only have the client part.  It's a bad practice to link client/server in the same code base, because client code and server code will change at a different rate.

I like the way Ayiga/go-kit-middlewarer generated files, in a specific directory that could be deleted and recreated at will. Files under the control of the generator shall be separated of the files given as example or as default.
